# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kathleen Hill
description: "Welcome to my data science portfolio, where I showcase my passion for extracting insights from data and driving decision-making through data-driven approaches. With a strong foundation in statistical analysis, machine learning, and data visualization, I am able to uncover hidden patterns, optimize processes, and inform strategic initiatives. Browse my projects to see how I've applied data science to real-world problems, and let's explore how I can help you unlock the full potential of your data. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
url: "https://kd365.github.io"
baseurl: "/kathleenhillportfolio.github.io"


#-------------------------------
# About Section
subtitle: Turning Data Into <span style="color:#f58506"> Knowledge </span>
location: "Alexandria, VA"
resume_url: /blob/master/img/Resume_Hill_2025.pdf
avatar_image: /img/headshot.jpeg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/kathleen-hill322/" # Add your linkedln handle
github: "https://github.com/kd365"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/









